/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useMemo, useEffect } from 'react'
import { useLoader } from 'react-three-fiber'
import { Shadow } from 'drei'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { meshopt } from '../../lib/meshopt'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/static/gltf/bicyclist.glb', meshopt())
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[5.7912002, 0.1524, 0]}>
        <group position={[0, 0.3083932, 0]}>
          <group
            position={[-0.0117149, 0.169418, -0.5973406]}
            rotation={[0.2832877, 0, Math.PI]}
            scale={[0.2346881, 0.2346881, 0.2346881]}>
            <group position={[-1.5893227, -2.8028951, -4.6520796]} scale={[0.0006418, 0.0006418, 0.0006418]}>
              <mesh material={materials.paintedmetal} geometry={nodes.mesh_0_0.geometry} />
              <mesh material={materials.metal} geometry={nodes.mesh_0_1.geometry} />
              <mesh material={materials.whitemetal} geometry={nodes.mesh_0_2.geometry} />
            </group>
          </group>
          <group
            position={[-0.0063791, 0.7981108, -0.3246999]}
            rotation={[-2.1364378, -2e-7, Math.PI / 2]}
            scale={[0.234688, 0.2346881, 0.234688]}>
            <group position={[-1.5893227, -2.8028951, -4.6520796]} scale={[0.0006418, 0.0006418, 0.0006418]}>
              <mesh material={materials.metal} geometry={nodes.mesh_1_0.geometry} />
              <mesh material={materials.rubber} geometry={nodes.mesh_1_1.geometry} />
            </group>
          </group>
          <group position={[-4.0769939, -0.2363475, -4.3831634]} rotation={[Math.PI / 2, 0, 0]}>
            <primitive object={nodes.mixamorigHips} />
          </group>
          <skinnedMesh
            material={materials['Texture Atlas.007']}
            geometry={nodes.mesh_2.geometry}
            skeleton={nodes.mesh_2.skeleton}
            position={[-1.5893227, -2.8028951, -4.6520796]}
            scale={[0.0006418, 0.0006418, 0.0006418]}
          />
          <group rotation={[Math.PI / 2, -1e-7, -Math.PI / 2]} scale={[0.2346881, 0.2346881, 0.2346881]}>
            <group position={[-1.5893227, -2.8028951, -4.6520796]} scale={[0.0006418, 0.0006418, 0.0006418]}>
              <mesh material={materials.metal} geometry={nodes.mesh_3_0.geometry} />
              <mesh material={materials.rubber} geometry={nodes.mesh_3_1.geometry} />
            </group>
          </group>
          <group
            position={[-0.0134187, 0.6095338, 0.1689749]}
            rotation={[-0.0575769, 1.5706755, 0]}
            scale={[0.2346881, 0.2346881, 0.2346881]}>
            <group position={[-1.5893227, -2.8028951, -4.6520796]} scale={[0.0006418, 0.0006418, 0.0006418]}>
              <mesh material={materials.rubber} geometry={nodes.mesh_4_0.geometry} />
              <mesh material={materials.metal} geometry={nodes.mesh_4_1.geometry} />
            </group>
          </group>
          <group
            position={[-0.011384, 0.0616881, 0.4954281]}
            rotation={[Math.PI / 2, -1e-7, -Math.PI / 2]}
            scale={[0.2346881, 0.2346881, 0.2346881]}>
            <group position={[-1.5893227, -2.8028951, -4.6520796]} scale={[0.0006418, 0.0006418, 0.0006418]}>
              <mesh material={materials.metal} geometry={nodes.mesh_5_0.geometry} />
              <mesh material={materials.rubber} geometry={nodes.mesh_5_1.geometry} />
            </group>
          </group>
          <group
            position={[-0.0118113, 0.0616881, -0.6619973]}
            rotation={[Math.PI / 2, -1e-7, -Math.PI / 2]}
            scale={[0.2346881, 0.2346881, 0.2346881]}>
            <group position={[-1.5893227, -2.8028951, -4.6520796]} scale={[0.0006418, 0.0006418, 0.0006418]}>
              <mesh material={materials.metal} geometry={nodes.mesh_6_0.geometry} />
              <mesh material={materials.rubber} geometry={nodes.mesh_6_1.geometry} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
