/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { Html } from 'drei'

function HtmlLabel({active, demand, setDemand}) {
  return (
    <Html zIndexRange={[950, 0]} style={{position: "relative"}}>
      <button 
        className={`outro-scene-label${ active ? ' outro-scene-label-active' : '' }`}
        onClick={() => setDemand(demand)}
      >
        <span className="outro-scene-label-number">{demand.index + 1}.</span> {demand.location}
      </button>
    </Html>
  )
}

export default function Model({demands, demand, setDemand, ...props}) {
  const group = useRef()
  const { nodes } = useLoader(GLTFLoader, './static/gltf/corporate-scene.gltf')
  const matcap = useLoader(THREE.TextureLoader, './static/textures/matcap.jpg')

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['Scene'].geometry}
        position={[0, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshMatcapMaterial
          matcap={matcap}
          attach="material"
          side={THREE.DoubleSide}
        />
      </mesh>
      <group>
        {demands.list().map(currentDemand => (
          <group
            key={currentDemand.id}
            position={currentDemand.position}
            rotation={[Math.PI / 2, 0, 0]}
          >
          <HtmlLabel
            active={currentDemand.id == demand.id}
            demand={currentDemand}
            setDemand={setDemand}
          />
        </group>
      ))}
      </group>
    </group>
  )
}
