/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { Html } from 'drei'

function HtmlLabel({number, text}) {
  return (
    <Html zIndexRange={[950, 0]} style={{position: "relative"}}>
      <div className="outro-scene-label">
        <span className="outro-scene-label-number">{number}.</span> {text}
      </div>
    </Html>
  )
}

export default function Model(props) {
  const group = useRef()
  const { nodes } = useLoader(GLTFLoader, './static/gltf/corporate-scene.gltf')
  const matcap = useLoader(THREE.TextureLoader, './static/textures/matcap.jpg')

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['Scene'].geometry}
        position={[0, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshMatcapMaterial
          matcap={matcap}
          attach="material"
          side={THREE.DoubleSide}
        />
      </mesh>
      <group>
        <group
          position={[25, 55, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <HtmlLabel number={1} text={"Board Room"} />
        </group>
        <group
          position={[0, 45, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <HtmlLabel number={2} text={"Financial Analysis"} />
        </group>
        <group
          position={[25, 35, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <HtmlLabel number={3} text={"Marketing Department"} />
        </group>
        <group
          position={[-10, 25, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <HtmlLabel number={4} text={"Research Lab"} />
        </group>
        <group
          position={[50, 20, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <HtmlLabel number={5} text={"Refinery"} />
        </group>
        <group
          position={[-40, 10, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <HtmlLabel number={6} text={"Community"} />
        </group>
        <group
          position={[5, 5, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <HtmlLabel number={7} text={"Lobby"} />
        </group>
      </group>
    </group>
  )
}
