/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { HTML } from 'drei'

const styles = {
  color: 'white',
  width: '100px'
}

export default function Model(props) {
  const group = useRef()
  const { nodes } = useLoader(GLTFLoader, './static/gltf/corporate-scene.gltf')
  const matcap = useLoader(THREE.TextureLoader, './static/textures/matcap.jpg')

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['Scene'].geometry}
        position={[0, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshMatcapMaterial
          matcap={matcap}
          attach="material"
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        position={[20, 55, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <HTML scaleFactor={100}>
          <div style={styles}>
            <span>1. Board Room</span>
          </div>
        </HTML>
      </mesh>
      <mesh
        position={[0, 45, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <HTML scaleFactor={100}>
          <div style={styles}>
            <span>2. Finance</span>
          </div>
        </HTML>
      </mesh>
      <mesh
        position={[25, 35, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <HTML scaleFactor={100}>
          <div style={styles}>
            <span>3. Marketing</span>
          </div>
        </HTML>
      </mesh>
      <mesh
        position={[-10, 25, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <HTML scaleFactor={100}>
          <div style={styles}>
            <span>4. Lab</span>
          </div>
        </HTML>
      </mesh>
      <mesh
        position={[50, 20, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <HTML scaleFactor={100}>
          <div style={styles}>
            <span>5. Refinery</span>
          </div>
        </HTML>
      </mesh>
      <mesh
        position={[-40, 10, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <HTML scaleFactor={100}>
          <div style={styles}>
            <span>6. Community</span>
          </div>
        </HTML>
      </mesh>
      <mesh
        position={[5, 5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <HTML scaleFactor={100}>
          <div style={styles}>
            <span>7. Lobby</span>
          </div>
        </HTML>
      </mesh>
    </group>
  )
}
