/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { meshopt } from '../../lib/meshopt'
import { Html } from 'drei'
import Fire from './Fire'

function HtmlLabel({active, demand, setDemand}) {
  return (
    <Html zIndexRange={[950, 0]} style={{position: "relative"}}>
      <button 
        className={`outro-scene-label${ active ? ' outro-scene-label-active' : '' }`}
        onClick={() => setDemand(demand)}
      >
        <span className="outro-scene-label-number">{demand.index + 1}.</span> {demand.location}
      </button>
    </Html>
  )
}

export default function Model({ demands, demand, setDemand, ...props }) {
  const group = useRef()
  const { nodes, materials, cameras } = useLoader(GLTFLoader, './static/gltf/corporate-building.glb', meshopt())

  return (
    <group ref={group} {...props}>
      <group position={[7.048502, -0.1523998, -1.2957768]}>
        <group position={[-52.5731583, -1, -30.7363758]} scale={[0.0056811, 0.0056811, 0.0056811]}>
          <mesh material={materials.Terrain} geometry={nodes.mesh_0_0.geometry} />
          <mesh material={materials['Building Exterior']} geometry={nodes.mesh_0_1.geometry} />
          <mesh material={materials.Trees} geometry={nodes.mesh_0_2.geometry} />
          <mesh material={materials.Refinery} geometry={nodes.mesh_0_3.geometry} />
          <mesh material={materials.Houses} geometry={nodes.mesh_0_4.geometry} />
        </group>
      </group>
      <Fire position={[-21.310915, 3, -1.9220421]} scale={[5, 5, 5]} />
      <group>
        {demands.list().map(currentDemand => (
          <group
            key={currentDemand.id}
            position={currentDemand.position}
            rotation={[Math.PI / 2, 0, 0]}
          >
          <HtmlLabel
            active={currentDemand.id == demand.id}
            demand={currentDemand}
            setDemand={setDemand}
          />
        </group>
      ))}
      </group>
    </group>
  )
}
