/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { meshopt } from '../../lib/meshopt'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/static/gltf/gas-station.glb', meshopt())

  const baseMaterial = materials['Base Lightmap'];
  baseMaterial.color = new THREE.Color(0x000000);
  const stationMaterial = materials['Gas Station Lightmap'];
  stationMaterial.color = new THREE.Color(0x000000);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI, 0.715585, -Math.PI]}>
        <group position={[-6.4007964, -0.0000024, -6.3999248]} scale={[0.0007814, 0.0007814, 0.0007814]}>
          <mesh material={baseMaterial} geometry={nodes.mesh_0_0.geometry} />
          <mesh material={stationMaterial} geometry={nodes.mesh_0_1.geometry} />
          <mesh material={materials.Black} geometry={nodes.mesh_0_2.geometry} />
        </group>
      </group>
    </group>
  )
}
