/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { meshopt } from '../lib/meshopt'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/bicyclist.glb', meshopt())
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[5.79, 0.15, 0]}>
        <group position={[0, 0.31, 0]}>
          <group position={[-0.01, 0.17, -0.6]} rotation={[0.28, 0, Math.PI]} scale={[0.23, 0.23, 0.23]}>
            <group position={[-1.59, -2.8, -4.65]} scale={[0, 0, 0]}>
              <mesh material={materials.paintedmetal} geometry={nodes.mesh_0_0.geometry} />
              <mesh material={materials.metal} geometry={nodes.mesh_0_1.geometry} />
              <mesh material={materials.whitemetal} geometry={nodes.mesh_0_2.geometry} />
            </group>
          </group>
          <group position={[-0.01, 0.8, -0.32]} rotation={[-2.14, 0, Math.PI / 2]} scale={[0.23, 0.23, 0.23]}>
            <group position={[-1.59, -2.8, -4.65]} scale={[0, 0, 0]}>
              <mesh material={materials.metal} geometry={nodes.mesh_1_0.geometry} />
              <mesh material={materials.rubber} geometry={nodes.mesh_1_1.geometry} />
            </group>
          </group>
          <group position={[-4.08, -0.24, -4.38]} rotation={[Math.PI / 2, 0, 0]}>
            <primitive object={nodes.mixamorigHips} />
          </group>
          <skinnedMesh
            material={materials['Texture Atlas.007']}
            geometry={nodes.mesh_2.geometry}
            skeleton={nodes.mesh_2.skeleton}
            position={[-1.59, -2.8, -4.65]}
            scale={[0, 0, 0]}
          />
          <group rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.23, 0.23, 0.23]}>
            <group position={[-1.59, -2.8, -4.65]} scale={[0, 0, 0]}>
              <mesh material={materials.metal} geometry={nodes.mesh_3_0.geometry} />
              <mesh material={materials.rubber} geometry={nodes.mesh_3_1.geometry} />
            </group>
          </group>
          <group position={[-0.01, 0.61, 0.17]} rotation={[-0.06, 1.57, 0]} scale={[0.23, 0.23, 0.23]}>
            <group position={[-1.59, -2.8, -4.65]} scale={[0, 0, 0]}>
              <mesh material={materials.rubber} geometry={nodes.mesh_4_0.geometry} />
              <mesh material={materials.metal} geometry={nodes.mesh_4_1.geometry} />
            </group>
          </group>
          <group position={[-0.01, 0.06, 0.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.23, 0.23, 0.23]}>
            <group position={[-1.59, -2.8, -4.65]} scale={[0, 0, 0]}>
              <mesh material={materials.metal} geometry={nodes.mesh_5_0.geometry} />
              <mesh material={materials.rubber} geometry={nodes.mesh_5_1.geometry} />
            </group>
          </group>
          <group position={[-0.01, 0.06, -0.66]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.23, 0.23, 0.23]}>
            <group position={[-1.59, -2.8, -4.65]} scale={[0, 0, 0]}>
              <mesh material={materials.metal} geometry={nodes.mesh_6_0.geometry} />
              <mesh material={materials.rubber} geometry={nodes.mesh_6_1.geometry} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
