/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { meshopt } from '../lib/meshopt'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/gas-station.glb', meshopt())
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.75, 0.86, -0.36]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_0.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.27, 1.12, -0.34]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_1.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.27, 1.07, -0.44]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_2.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.64, 1.12, -0.34]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_3.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.64, 1.07, -0.44]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_4.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.46, 1.07, 0.15]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_5.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.46, 1.1, 0.34]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_6.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.27, 1.07, 0.4]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_7.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.64, 1.07, 0.4]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_8.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.46, 2.02, 0.15]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_9.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.46, 1.07, -0.15]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_10.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.76, 1.22, 0.15]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_11.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.15, 1.22, 0.15]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_12.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.15, 0.93, 0.31]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_13.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.75, 0.86, 0.36]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_14.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.27, 1.12, 0.34]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_15.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.27, 1.07, 0.44]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_16.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.64, 1.12, 0.34]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_17.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.64, 1.07, 0.44]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_18.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-1.52, 3.61, 3.81]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_19.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.46, 1.1, -0.34]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_20.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.01, 0.38, -0.03]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_21.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-2.02, 1.68, 0]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_22.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[2.02, 1.68, 0]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_23.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-0.02, 2.97, -0.03]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_24.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 3.12, 3.05]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_25.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 3.01, 3.05]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_26.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 3.22, 3.05]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_27.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 3.25, 3.35]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_28.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.27, 1.07, -0.4]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_29.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 3.22, 3.66]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_30.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 2.06, 3.66]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_31.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 0.76, 3.66]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_32.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 0.53, 3.66]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_33.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 3.12, -3.05]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_34.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 3.01, -3.05]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_35.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 3.22, -3.05]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_36.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 3.25, -3.35]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_37.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 3.22, -3.66]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_38.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 2.06, -3.66]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_39.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.64, 1.07, -0.4]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_40.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 0.76, -3.66]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_41.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[1.52, 0.53, -3.66]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_42.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-1.52, 3.12, -3.05]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_43.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-1.52, 3.01, -3.05]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_44.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-1.52, 3.22, -3.05]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_45.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-1.52, 3.25, -3.35]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_46.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-1.52, 3.22, -3.66]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_47.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-1.52, 2.06, -3.66]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_48.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-1.52, 0.76, -3.66]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_49.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[-1.52, 0.53, -3.66]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_50.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.46, 2.02, -0.15]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_51.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.76, 1.22, -0.15]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_52.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.15, 1.22, -0.15]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_53.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.15, 0.93, -0.31]}>
        <mesh
          material={materials.Default}
          geometry={nodes.mesh_54.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.03, 0.15, -0.01]}>
        <mesh
          material={materials.Pavement}
          geometry={nodes.mesh_55.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0, 0.08, 0]}>
        <mesh
          material={materials.Road}
          geometry={nodes.mesh_56.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.01, 0.38, -3.7]}>
        <mesh
          material={materials.Pavement}
          geometry={nodes.mesh_57.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
      <group position={[0.01, 0.38, 3.7]}>
        <mesh
          material={materials.Pavement}
          geometry={nodes.mesh_58.geometry}
          position={[-6.4, -3.15, -6.4]}
          scale={[0, 0, 0]}
        />
      </group>
    </group>
  )
}
